name: KBOT-CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  TARGETOS: linux
  TARGETARCH: amd64

# Глобальні дефолти (можна прибрати, якщо задаєш на job-рівні)
permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    # ВАЖЛИВО: не перезаписуй без потреби. Якщо треба — збережи packages: write
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        env:
          APP: "kbot"
        run: make image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      # потрібно для git push
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set VERSION
        run: echo "VERSION=$(git describe --tags --abbrev=0 --always)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Helm values
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "[skip ci] update version $VERSION" || echo "No changes"
          git push
